---
title: "PlotBuilder"
author: "Jonathan"
date: "`r Sys.Date()`"
output: html_document
self-contained: True
---

```{r}
source('Setup.R')
source('DataImport.R')
source('NutritionCleaning.R')
```

```{r}
CorrectDatDF <- data_cleanComFull
CorrectDatDF$Year <- as.factor(CorrectDatDF$Year)
for(i in 2:length(CorrectDatDF)) {

print(colnames(CorrectDatDF[i]))
print(ggplot(data = CorrectDatDF) + geom_density(aes(x = CorrectDatDF[,i], fill = Year, color = Year, after_stat(scaled)),alpha = 0.2, adjust = 3.5))
mean <- mean(CorrectDatDF[,i], na.rm = T)
sum_of_squares <- sum((CorrectDatDF[,i] - mean)^2, na.rm = T)
print(paste("Mean     : ", mean, sep = ""))
print(paste("Sum'O'^2 : ", sum_of_squares, sep = ""))
print(paste("Variance : ", var(CorrectDatDF[,i], na.rm = T), sep = ""))
print(paste("Stdev    : ", sd(CorrectDatDF[,i], na.rm = T), sep = ""))
print(paste("Kurtosis : ", kurtosis(CorrectDatDF[,i], na.rm = T), sep = ""))
print(paste("Skewness : ", skewness(CorrectDatDF[,i], na.rm = T), sep = ""))
cat("\n")
}
```

