---
title: "PlotBuilder"
format: html
editor: visual
self-contained: true
---

```{r, eval=FALSE}
CorrectDatDF <- BMMerge
CorrectDatDF$Year <- as.factor(CorrectDatDF$Year)
print(ggplot(data = CorrectDatDF) + geom_density(aes(x = CorrectDatDF[,3], fill = Year, color = Year, after_stat(scaled)),alpha = 0.2, adjust = 2))
```

```{r}
source('Packages.R')
source('DataImport.R')
source("NutritionCleaning.R")
source('DataMerging.R')
```

```{r}
DFList <- list(IncomeMerge, DemMerge, BMMerge, D1Merge, D2Merge)
for (j in 1:5){
CorrectDatDF <- as.data.frame(DFList[[j]])
CorrectDatDF$Year <- as.factor(CorrectDatDF$Year)
for(i in 2:length(CorrectDatDF)) {
print(colnames(CorrectDatDF[,i]))
print(attr(CorrectDatDF[,i],"label"))
print(summary(CorrectDatDF[,i]))
try(print(summary(aov(CorrectDatDF[,i]~CorrectDatDF$Year))))
try(print(ggplot(data = CorrectDatDF) + geom_violin(aes(y = CorrectDatDF[,i], x = Year, fill = Year, color = Year),alpha = 0.2, adjust = 1.2, na.rm = T)), silent = T)
try(print(ggplot(data = CorrectDatDF) + geom_density(aes(x = CorrectDatDF[,i], fill = Year, color = Year, after_stat(scaled)),alpha = 0.2, adjust = 2)))
}}
```



```{r}
DFList <- list(IncomeMerge, DemMerge, data_cleanComFMerge)
AllMerge <- BMMerge
for (i in length(DFList)){
AllMerge <- merge(AllMerge, DFList[i], by = "SEQN")
}
```

```{r}
CorrectDatDF <- AllMerge
for(i in 2:length(CorrectDatDF)) {
print(colnames(CorrectDatDF[,i]))
#print(attr(CorrectDatDF[,i],"label"))
print(summary(CorrectDatDF[,i]))
try(print(summary(t.test(CorrectDatDF[,i]~CorrectDatDF$BMXBMI))))
try(print(ggplot(data = CorrectDatDF) + geom_violin(aes(y = CorrectDatDF[,i], x = BMXBMI, fill = BMXBMI, color = BMXBMI),alpha = 0.2, adjust = 1.2, na.rm = T)), silent = T)
try(print(ggplot(data = CorrectDatDF) + geom_density(aes(x = CorrectDatDF[,i], fill = BMXBMI, color = BMXBMI, after_stat(scaled)),alpha = 0.2, adjust = 2)))
}
```

