---
title: "MainDoc"
format: html
editor: visual
self-contained: true
---

```{r}
#seed(91)
source('Packages.R') 
source('DataImport.R')
source('NutritionCleaning.R')
source('DataMerging.R')
source('CreatingVariables.R')
source('CreatingGroupedDFs.R')
```

```{r, eval = F}
source('CreatingVariables.R')
```

```{r, eval = F}
source('CreatingGroupedDFs.R')
```

```{r, eval = F}
source('Corrplot.R')
```

```{r}
#Color by P-val, need to correct for P-val due to so many T-tests
#Stepwise regression, AIC, second order
#Run PCA on predictors

CorrCols <- c(2, 6, 10, 119, 120, 125)

PMat <- cor.mtest(FullMergeCorr, conf.level = .98)

#corrplot::corrplot(FullMergeCorr[CorrCols,-CorrCols], type = "upper")

corrplot::corrplot(PMat$p[CorrCols,-CorrCols],
#lowCI = PMat$lowCI[CorrCols,-CorrCols],
#uppCI = PMat$uppCI[CorrCols,-CorrCols],
method = "color", tl.cex = .45, is.corr = FALSE, tl.srt = 45, col = colorRampPalette(c("forestgreen", "white", "red"))(150))
```

```{r}
AllMerge[is.na(AllMerge)] <- 0
NonNumeric <- which(!sapply(AllMerge, is.numeric))
PCA <- prcomp(AllMerge[,-NonNumeric])
PCA <- summary(PCA)
PCAVariance <- PCA$importance[,1:6]

#lm <- lm(AllMerge$HWR~PCA$x[,1:126])
#model <- pcr(BMXWAIST~.,ncomp = 6 ,data = AllMerge[,-NonNumeric], scale = T, validation = "CV")
```

```{r}
#AllMerge <- AllMerge[,c(1:118,124)]
intercept <- lm(HWR~1, data = AllMerge[,-c(1:10, 119:123,125:129, 84)])

glm <- lm(HWR~., data = AllMerge[,-c(1:10, 119:123,125:129, 84)])
Stepwise <- step(intercept, trace=0, steps = 10, direction = "both", scope = formula(glm))
summary(Stepwise)
# Top 10 - Both
# Vigorous Rec activities
# FatPercent
# On weight loss or low cal diet
# Race/Hispanic Origin
# Education level (over 20)
# Age in Years
# Moderate work activity
# Moisture
# Magnesium
# Carb Percent
```

```{r}
plot(AllMerge$BMXBMI ~ AllMerge$BMXWAIST)
```

```{r}
plot(AllMerge$DR1TKCAL ~ AllMerge$BMXWAIST)
```

```{r}
plot(AllMerge$DR1TKCAL ~ AllMerge$BMXWAIST)
```

```{r}
plot(AllMerge$DR1TKCAL ~ AllMerge$DR1TNUMF)
```

```{r}
ggplot(data = AllMergeYear, aes(Year)) + geom_point(aes(y))
```

```{r}
histogram(AllMerge$BMIObeseNum)
```

```{r}
histogram(AllMerge$RFMObese)
```
